location = "bench-client-1"
server_id = 1
server_address = "127.0.0.1:8001"
summary_filepath = "./logs/client-1.json"
output_filepath  = "./logs/client-1.csv"

# warm-up phase
[[requests]]
duration_sec     = 1
requests_per_sec = 10
read_ratio       = 0.25

# sustained benchmark phase
[[requests]]
duration_sec     = 10
requests_per_sec = 20
read_ratio       = 0.25
